use async_stream::stream;
use claco_termulator::{Session, SessionOptions};
use futures::Stream;
#[cfg(feature = "tui-parsing")]
use regex::Regex;
use std::sync::Arc;

macro_rules! log_file {
    ($($arg:tt)*) => {{
        use std::io::Write;
        if let Ok(mut file) = std::fs::OpenOptions::new().create(true).append(true).open("/tmp/claco-agent.log") {
            let _ = writeln!(file, $($arg)*);
        }
    }};
}

/// Represents a discrete block of output or action generated by Claude Code.
#[derive(Debug, Clone, PartialEq)]
pub enum ClacoResponse {
    Text(String),
    ToolCall {
        name: String,
        args: serde_json::Value,
    },
}

/// A handle to an active terminal session running Claude Code.
pub struct ClacoSession {
    session: Arc<Session>,
    #[cfg(not(feature = "tui-parsing"))]
    jsonl_state: Arc<std::sync::Mutex<JsonlState>>,
}

#[cfg(not(feature = "tui-parsing"))]
struct JsonlState {
    spawn_time: std::time::SystemTime,
    path: Option<std::path::PathBuf>,
    offset: u64,
    cwd: Option<std::path::PathBuf>,
}

impl ClacoSession {
    /// Spawns the Claude Code CLI in a pseudo-terminal and waits for it to become ready.
    /// It automatically accepts prompts related to trusting the active workspace.
    pub async fn spawn(
        cwd: Option<std::path::PathBuf>,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        #[cfg(not(feature = "tui-parsing"))]
        let spawn_time = std::time::SystemTime::now();

        let options = SessionOptions {
            program: "claude".to_string(),
            args: vec![],
            cols: 120,
            rows: 40,
            cwd: cwd.clone(),
        };
        let session = Session::spawn(options)?;

        // Give it a moment to render the first screen so we don't race
        session.wait_for_activity().await?;

        loop {
            let text = session.get_text().await.unwrap_or_default();

            if text.contains("Yes, I accept") {
                session.input().down().enter();
                session.wait_for_activity().await?;
            } else if text.contains("Yes, I trust this folder") {
                session.input().enter();
                session.wait_for_activity().await?;
            } else if regex::Regex::new("Claude Code v\\d+\\.\\d+\\.\\d+")
                .unwrap()
                .is_match(&text)
            {
                break;
            } else {
                tokio::time::sleep(tokio::time::Duration::from_millis(200)).await;
            }
        }

        session.wait_for_idle().await?;
        session.serve_ipc().await?;

        Ok(Self {
            session: Arc::new(session),
            #[cfg(not(feature = "tui-parsing"))]
            jsonl_state: Arc::new(std::sync::Mutex::new(JsonlState {
                spawn_time,
                path: None,
                offset: 0,
                cwd,
            })),
        })
    }

    /// Submits a query to Claude and streams responses continuously.
    pub async fn send(
        &self,
        prompt: &str,
    ) -> Result<impl Stream<Item = ClacoResponse>, Box<dyn std::error::Error>> {
        let session = self.session.clone();
        let prompt_str = prompt.to_string();

        session.input().text(prompt);
        log_file!("Sending prompt text: {}", prompt_str);
        session.wait_for_activity().await?;
        log_file!("Prompt sent");
        session.input().enter();

        Ok(stream! {
            let mut rx_event = session.subscribe();
            log_file!("Subscribed");

            #[cfg(feature = "tui-parsing")]
            let mut last_blocks = Vec::new();

            #[cfg(not(feature = "tui-parsing"))]
            let shared_jsonl_state = self.jsonl_state.clone();

            let mut finished = false;

            while !finished {
                log_file!("Waiting for event");
                tokio::select! {
                    res = rx_event.recv() => {
                        log_file!("Event received: {:?}", &res);
                        if res.is_err() { break; }
                        let _ = session.wait_for_idle().await;

                        #[cfg(feature = "tui-parsing")]
                        let (is_finished, new_blocks) = process_session_text(&session, &prompt_str, &mut last_blocks).await;

                        #[cfg(not(feature = "tui-parsing"))]
                        let (is_finished, new_blocks) = process_session_jsonl(&session, &prompt_str, &shared_jsonl_state).await;
                        if is_finished {
                            log_file!("{:?}", &session.get_text().await.unwrap());
                        }

                        finished = is_finished;
                        for block in new_blocks {
                            yield block;
                        }
                    }
                    _ = tokio::time::sleep(tokio::time::Duration::from_millis(100)) => {
                        log_file!("Checking if finished");
                        finished = check_is_finished(&session, &prompt_str).await;
                        if finished {
                            log_file!("Finished");
                            log_file!("{:?}", &session.get_text().await.unwrap());
                        }
                    }
                }
            }
        })
    }
}

async fn check_is_finished(session: &Session, prompt: &str) -> bool {
    let text = match session.get_text().await {
        Ok(t) => t,
        Err(_) => return true,
    };
    is_finished(&text, prompt)
}

fn is_finished(text: &str, prompt: &str) -> bool {
    if text.contains("esc to interrupt") {
        log_file!("Esc to interrupt");
        return false;
    }

    if text.contains("? for shortcuts") {
        log_file!("Finished");
        return true;
    }

    let first_line = prompt.lines().next().unwrap_or("").trim();
    let prompt_marker = format!("❯ {}", first_line);

    if let Some(idx) = text.rfind(&prompt_marker) {
        let after_prompt = &text[idx + prompt_marker.len()..];
        for line in after_prompt.lines().skip(1) {
            if line.trim().starts_with('❯') {
                log_file!("Finished");
                return true;
            }
        }
    }

    // Fallback for empty/multiline prompts where exact prompt marker isn't found
    // or isn't followed by another line, but the last non-empty line is `❯`
    let mut non_empty_lines = text.lines().rev().filter(|l| !l.trim().is_empty());
    if let Some(last_line) = non_empty_lines.next() {
        if last_line.trim() == "❯" {
            return true;
        }
    }

    false
}

#[cfg(feature = "tui-parsing")]
async fn process_session_text(
    session: &Session,
    prompt: &str,
    last_blocks: &mut Vec<ClacoResponse>,
) -> (bool, Vec<ClacoResponse>) {
    let text = match session.get_text().await {
        Ok(t) => t,
        Err(_) => return (true, vec![]),
    };

    let blocks = parse_responses(&text, prompt);

    let mut new_blocks = Vec::new();
    for (i, block) in blocks.iter().enumerate() {
        if i >= last_blocks.len() || &last_blocks[i] != block {
            new_blocks.push(block.clone());
        }
    }

    *last_blocks = blocks;

    (is_finished(&text, prompt), new_blocks)
}

#[cfg(feature = "tui-parsing")]
fn parse_responses(text: &str, prompt: &str) -> Vec<ClacoResponse> {
    let mut blocks = Vec::new();

    let prompt_marker = format!("❯ {}", prompt);
    let parts: Vec<&str> = text.split(&prompt_marker).collect();
    if parts.len() < 2 {
        return blocks;
    }

    let after_prompt = parts.last().unwrap();
    let block_splits: Vec<&str> = after_prompt.split(|c| c == '⏺' || c == '●').collect();

    for split in block_splits.iter() {
        parse_block(split.trim(), &mut blocks);
    }

    blocks
}

#[cfg(feature = "tui-parsing")]
fn parse_block(trimmed: &str, blocks: &mut Vec<ClacoResponse>) {
    if trimmed.is_empty() {
        return;
    }

    let re_tool = Regex::new(r"^(\w+)\(([^)]*)\)").unwrap();
    if let Some(caps) = re_tool.captures(trimmed) {
        let args_str = caps[2].trim();
        let mut map = serde_json::Map::new();

        for pair in args_str.split(',') {
            if let Some((k, v)) = pair.split_once('=') {
                let key = k.trim().to_string();
                let val = v.trim().trim_matches('"').to_string();
                map.insert(key, serde_json::Value::String(val));
            }
        }

        let args = if map.is_empty() && !args_str.is_empty() {
            serde_json::Value::String(args_str.to_string())
        } else {
            serde_json::Value::Object(map)
        };

        blocks.push(ClacoResponse::ToolCall {
            name: caps[1].to_string(),
            args,
        });

        let matched_len = caps.get(0).unwrap().end();
        let remaining = trimmed[matched_len..].trim();

        if let Some(text) = extract_useful_text(remaining) {
            blocks.push(ClacoResponse::Text(text));
        }
    } else {
        if let Some(text) = extract_useful_text(trimmed) {
            blocks.push(ClacoResponse::Text(text));
        }
    }
}

#[cfg(feature = "tui-parsing")]
fn extract_useful_text(text: &str) -> Option<String> {
    let mut cleaned = String::new();
    let mut has_useful_text = false;

    for line in text.lines() {
        let tl = line.trim();
        if tl.starts_with('❯') || is_ui_artifact(tl) {
            continue;
        }

        has_useful_text = true;
        cleaned.push_str(line);
        cleaned.push('\n');
    }

    let cleaned = cleaned.trim();
    if has_useful_text && !cleaned.is_empty() {
        Some(cleaned.to_string())
    } else {
        None
    }
}

#[cfg(feature = "tui-parsing")]
fn is_ui_artifact(line: &str) -> bool {
    line.starts_with('·')
        || line.starts_with('⎿')
        || line.starts_with('─')
        || line.starts_with('✳')
        || line.starts_with('✶')
        || line.starts_with('✢')
        || line.starts_with('✻')
        || line.starts_with('✽')
        || line.starts_with("Reading")
        || line.starts_with("Read ")
        || line.contains("esc to interrupt")
        || line.contains("? for shortcuts")
}

#[cfg(not(feature = "tui-parsing"))]
fn find_session_jsonl(
    spawn_time: std::time::SystemTime,
    override_cwd: Option<std::path::PathBuf>,
) -> Option<std::path::PathBuf> {
    let mut path = dirs::home_dir()?;
    path.push(".claude");
    path.push("projects");
    let cwd = if let Some(cwd) = override_cwd {
        let scwd = cwd.to_string_lossy().to_string();
        log_file!("Using overridden CWD: {}", scwd);
        scwd
    } else {
        let scwd = std::env::current_dir().ok()?.to_string_lossy().to_string();
        log_file!("Using current process CWD: {}", scwd);
        scwd
    };

    // Claude replaces non-alphanumeric characters with '-'
    let mut escaped = String::new();
    for c in cwd.chars() {
        if c.is_ascii_alphanumeric() {
            escaped.push(c);
        } else {
            escaped.push('-');
        }
    }
    path.push(escaped);

    let mut latest = None;
    let mut latest_time = spawn_time;

    let entries = std::fs::read_dir(&path).ok()?.flatten().collect::<Vec<_>>();
    log_file!("Path: {:#?}, entries: {:#?}", path, &entries);
    for entry in entries {
        let p = entry.path();
        if p.extension().and_then(|e| e.to_str()) != Some("jsonl") {
            continue;
        }

        log_file!("metadata: {:#?}", entry);
        if let Ok(metadata) = entry.metadata() {
            if let Ok(time) = metadata.modified() {
                if time >= latest_time {
                    latest_time = time;
                    latest = Some(p);
                }
            }
        }
    }

    latest
}

#[cfg(not(feature = "tui-parsing"))]
async fn process_session_jsonl(
    session: &Session,
    prompt: &str,
    jsonl_state_arc: &Arc<std::sync::Mutex<JsonlState>>,
) -> (bool, Vec<ClacoResponse>) {
    let mut new_blocks = Vec::new();
    let is_finished = check_is_finished(session, prompt).await;

    let mut state = jsonl_state_arc.lock().unwrap();

    log_file!("stte-path: {:#?}", state.path);
    if state.path.is_none() {
        state.path = find_session_jsonl(state.spawn_time, state.cwd.clone());
    }

    let path_clone = state.path.clone();
    let unparsed_content = {
        let mut content = read_new_jsonl_content(path_clone.as_deref(), &mut state.offset);
        if is_finished && content.is_empty() {
            // Give Claude a moment to flush its JSONL if the terminal just closed or IDLE'd.
            tokio::time::sleep(tokio::time::Duration::from_millis(150)).await;
            content = read_new_jsonl_content(path_clone.as_deref(), &mut state.offset);
        }
        content
    };
    log_file!("Unparsed content: {:?}", unparsed_content);

    if unparsed_content.is_empty() {
        return (is_finished, new_blocks);
    }

    for line in unparsed_content.lines() {
        let msg: serde_json::Value = match serde_json::from_str(line) {
            Ok(v) => v,
            Err(_) => continue,
        };

        if msg.get("type").and_then(|v| v.as_str()) != Some("assistant") {
            continue;
        }

        if let Some(contents) = msg
            .get("message")
            .and_then(|m| m.get("content"))
            .and_then(|c| c.as_array())
        {
            for c in contents {
                if let Some(block) = parse_jsonl_content_block(c) {
                    new_blocks.push(block);
                }
            }
        }
    }

    (is_finished, new_blocks)
}

#[cfg(not(feature = "tui-parsing"))]
fn read_new_jsonl_content(path: Option<&std::path::Path>, offset: &mut u64) -> String {
    log_file!("Reading new JSONL content: {:?}", path);
    use std::io::{Read, Seek, SeekFrom};

    let path = match path {
        Some(p) => p,
        None => return String::new(),
    };

    let mut file = match std::fs::File::open(path) {
        Ok(f) => f,
        Err(_) => return String::new(),
    };

    if file.seek(SeekFrom::Start(*offset)).is_err() {
        return String::new();
    }

    let mut content = String::new();
    if file.read_to_string(&mut content).is_ok() {
        *offset += content.len() as u64;
        content
    } else {
        String::new()
    }
}

#[cfg(not(feature = "tui-parsing"))]
fn parse_jsonl_content_block(c: &serde_json::Value) -> Option<ClacoResponse> {
    let block_type = c.get("type").and_then(|v| v.as_str());

    if block_type == Some("text") {
        let text = c.get("text").and_then(|v| v.as_str())?;
        return Some(ClacoResponse::Text(text.to_string()));
    }

    if block_type == Some("tool_use") {
        let name = c.get("name").and_then(|v| v.as_str())?;
        let input = c.get("input").and_then(|v| v.as_object())?;

        let args = serde_json::Value::Object(input.clone());

        return Some(ClacoResponse::ToolCall {
            name: name.to_string(),
            args,
        });
    }

    None
}
